server:
  port: 8080

spring:
  application:
    name: GoGym
  profiles:
    active: prod

  data:
    redis:
      host: ENC(BAyrDQ2US9n4xvHaYjIbiMoftLiRNAta)
      port: 6379
      timeout: 2000

  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(I40C+Y7Xj8nz0Y3XR449v/QoMLC2N0Un/9TsprSMwl0=)
    password: ENC(Vdn2hP0Eh+ANLVA1Srhx3rxF0Uhke3UExvuPzYaW278=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jwt:
    secret: ENC(sz14IJLNwiaaHMqAtImz76SKb3nSkiq8FlPPYwToQFyAs1uMSprSqv21vvqUl1An)
    validity: ENC(iSNAc2YD8ecXGkZWP+5f0A==)

logging:
  level:
    org:
      hibernate:
        SQL: info
        type:
          descriptor: trace

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}

portone:
  secret: ENC(Yae9m6UdFdavIg+60o/aoAP5jG7K4gwTIIy/I8FLCsp8PYOcIb0sfwr3wd8Z37XGke+83s1e4VTEv9OtMwV3wmnOWTeXJJ1JqxmGc8VKHFzyR6FJ4YoSPfwKjsBrUwB1)
  webhook:
    secret: ENC(rNgfIF0802rxis0Md6mRpdGH3WpdHA7XxabMdLFZXV6TWgeXAyUjfsFdffaqMBOfJlKSro6UCy3Krc2nOUfRNw==)
