server:
  port: 8080

spring:
  mvc:
    async:
      request-timeout: 60000

  application:
    name: GoGym
  profiles:
    active: dev

  data:
    redis:
      host: ENC(BAyrDQ2US9n4xvHaYjIbiMoftLiRNAta)
      port: 6379
      timeout: 2000

  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(I40C+Y7Xj8nz0Y3XR449v/QoMLC2N0Un/9TsprSMwl0=)
    password: ENC(Vdn2hP0Eh+ANLVA1Srhx3rxF0Uhke3UExvuPzYaW278=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jwt:
    secret: ENC(sz14IJLNwiaaHMqAtImz76SKb3nSkiq8FlPPYwToQFyAs1uMSprSqv21vvqUl1An)
    validity: ENC(iSNAc2YD8ecXGkZWP+5f0A==)

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org:
      hibernate:
        SQL: info
        type:
          descriptor: trace

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}

portone:
  secret: ENC(EpRw1xyNsEfEArSn8H91SeUZR2M+HGVHKRqZ4bVDlKdW6sANl9+3ZmgJK/AI+GU7/G94pNpcAzDQpfdMWrkqJ5GcxR3TCKFscazOpT1ZM30RD+OVOgdpd3XQ/yErUozs)
  webhook:
    secret: ENC(rNgfIF0802rxis0Md6mRpdGH3WpdHA7XxabMdLFZXV6TWgeXAyUjfsFdffaqMBOfJlKSro6UCy3Krc2nOUfRNw==)

cloud:
  aws:
    credentials:
      access-key: ENC(FQO19gAuU2P7csP5hfomdMovGImuxHYq5LvlalfYMzE=)
      secret-key: ENC(X3c52PgIRV7t9j/hYqjDLsTOqKMnVvL6u1/++8efNWQR428eaMzePDJ81ONHbHA4R7KP53z8ORs=)
    S3:
      bucket: ENC(GzhWzOfXoVXPUdHytq5szeRWxAbUpiVY)
    region:
      static: ENC(eilntHEIo5VEIK4m88ADKT/huIwY7Ijx)
    stack:
      auto: false
